#!/usr/bin/env node
// Turns `agent-versions --json` output into GitHub Action outputs.
import { readFileSync } from 'node:fs';

const result = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const RANK = { patch: 1, minor: 2, major: 3 };
const counts = { patch: 0, minor: 0, major: 0 };
let level = 'none';
const rows = [];
for (const file of result.files) {
  for (const d of file.dependencies) {
    if (d.status !== 'outdated') continue;
    const l = d.level ?? (d.major ? 'major' : 'minor');
    counts[l]++;
    if ((RANK[l] ?? 0) > (RANK[level] ?? 0)) level = l;
    rows.push(`| \`${d.alias ?? d.name}\` | ${file.path} | \`${d.current}\` | \`${d.next}\` | ${l === 'major' ? '**major**' : l} |`);
  }
}
const heldFresh = result.files.flatMap((f) => f.dependencies).filter((d) => d.status === 'held' && /minimum age/.test(d.reason ?? ''));
const held = result.summary.held ? `\n${result.summary.held} major update(s) were held back by \`--no-major\`.\n` : '';
const body = rows.length
  ? [
      `Updates ${rows.length} dependenc${rows.length === 1 ? 'y' : 'ies'} to the latest releases.`,
      '',
      '| Package | Manifest | From | To | Change |',
      '|---|---|---|---|---|',
      ...rows,
      held,
      heldFresh.length ? `${heldFresh.length} release(s) are newer than the minimum release age and will be picked up in a later run.\n` : '',
      `Largest change: **${level}**. Lockfiles were refreshed with install scripts disabled.`,
      '',
      '_Generated by [agent-versions](https://github.com/AndrewTtofi/versions)._',
    ].join('\n')
  : 'All dependencies are on the latest releases.';

const delimiter = `EOF_${Math.random().toString(36).slice(2)}`;
console.log(`outdated=${result.summary.outdated}`);
console.log(`level=${level}`);
for (const [k, v] of Object.entries(counts)) console.log(`${k}=${v}`);
console.log(`report<<${delimiter}\n${body}\n${delimiter}`);
