#!/usr/bin/env node
// Turns `agent-versions --json` output into GitHub Action outputs.
import { readFileSync } from 'node:fs';

const result = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const rows = [];
for (const file of result.files) {
  for (const d of file.dependencies) {
    if (d.status !== 'outdated') continue;
    rows.push(`| \`${d.alias ?? d.name}\` | ${file.path} | \`${d.current}\` | \`${d.next}\` | ${d.major ? '**major**' : ''} |`);
  }
}
const held = result.summary.held ? `\n${result.summary.held} major update(s) were held back by \`--no-major\`.\n` : '';
const body = rows.length
  ? [
      `Updates ${rows.length} dependenc${rows.length === 1 ? 'y' : 'ies'} to the latest releases.`,
      '',
      '| Package | Manifest | From | To | |',
      '|---|---|---|---|---|',
      ...rows,
      held,
      'Lockfiles are not regenerated by this job; run your package manager install locally or add a step for it.',
      '',
      '_Generated by [agent-versions](https://github.com/AndrewTtofi/versions)._',
    ].join('\n')
  : 'All dependencies are on the latest releases.';

const delimiter = `EOF_${Math.random().toString(36).slice(2)}`;
console.log(`outdated=${result.summary.outdated}`);
console.log(`report<<${delimiter}\n${body}\n${delimiter}`);
