// Human-readable VERSIONS.md generated from the snapshot.

const ECOSYSTEM_LABELS = { npm: 'npm', pypi: 'PyPI', cargo: 'crates.io', go: 'Go modules' };

function toolVersion(tool) {
  if (tool.release) return `\`${tool.release}\``;
  const primary = Object.values(tool.packages ?? {}).flatMap((p) => Object.entries(p))[0];
  if (primary) return `\`${primary[1] ?? '?'}\``;
  return '—';
}

const esc = (s) => String(s).replace(/[\\|`<>]/g, (ch) => `\\${ch}`);

export function renderMarkdown(snapshot) {
  const out = [];
  out.push('# Latest versions', '');
  out.push(`> Auto-generated by [\`scripts/collect.js\`](scripts/collect.js) at **${snapshot.generatedAt}**. Do not edit by hand.`, '');
  out.push('## AI coding tools', '');
  out.push('| Tool | Latest | Packages | Install |', '|---|---|---|---|');
  for (const [id, tool] of Object.entries(snapshot.tools)) {
    const pkgs = Object.entries(tool.packages ?? {})
      .flatMap(([eco, p]) => Object.entries(p).map(([n, v]) => `${eco}:\`${n}\`@${v ?? '?'}`))
      .join('<br>');
    out.push(`| [${esc(tool.name)}](${tool.homepage}) (\`${id}\`) | ${toolVersion(tool)} | ${pkgs || '—'} | \`${esc(tool.install ?? '')}\` |`);
  }
  out.push('');

  out.push('## Dependencies used by these tools', '');
  out.push('| Ecosystem | Packages |', '|---|---|');
  for (const [eco, pkgs] of Object.entries(snapshot.packages)) {
    out.push(`| ${ECOSYSTEM_LABELS[eco] ?? eco} | ${Object.keys(pkgs).length} |`);
  }
  out.push('');

  // The most widely shared dependencies are the most useful at a glance.
  const shared = Object.entries(snapshot.packages)
    .flatMap(([eco, pkgs]) => Object.entries(pkgs).map(([name, p]) => ({ eco, name, ...p })))
    .filter((p) => p.usedBy.length > 1)
    .sort((a, b) => b.usedBy.length - a.usedBy.length || a.name.localeCompare(b.name));
  if (shared.length) {
    out.push('### Shared by more than one tool', '');
    out.push('| Package | Ecosystem | Latest | Used by |', '|---|---|---|---|');
    for (const p of shared) out.push(`| \`${esc(p.name)}\` | ${p.eco} | \`${p.latest}\` | ${p.usedBy.join(', ')} |`);
    out.push('');
  }

  for (const [eco, pkgs] of Object.entries(snapshot.packages)) {
    out.push(`<details><summary><strong>All ${ECOSYSTEM_LABELS[eco] ?? eco} packages (${Object.keys(pkgs).length})</strong></summary>`, '');
    out.push('| Package | Latest | Used by |', '|---|---|---|');
    for (const [name, p] of Object.entries(pkgs)) out.push(`| \`${esc(name)}\` | \`${p.latest}\` | ${p.usedBy.join(', ')} |`);
    out.push('', '</details>', '');
  }

  if (snapshot.errors?.length) {
    out.push(`<details><summary>${snapshot.errors.length} lookup problems during the last run</summary>`, '');
    for (const e of snapshot.errors) out.push(`- ${esc(e.tool ?? '')} ${esc(e.package ?? e.repo ?? e.releases ?? e.versionUrl ?? '')}: ${esc(e.error)}`);
    out.push('', '</details>', '');
  }
  return out.join('\n');
}
